    
       ###CloudFormation Template to triggre CodeBuild with EventBridge Schedule

AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyScheduledTrigger:
   Type: 'AWS::Scheduler::Schedule'
   Properties:
     FlexibleTimeWindow:
       Mode: 'OFF'
     Name: Test  
     ScheduleExpression: cron(0 0 * * ? *)
     State: ENABLED
     Target:
       Arn:  'arn:aws:codebuild:<Region>:<AccountNumber>:project/<codeBuildName>'
       RoleArn: '##while creating EventBridge Schedule Role ARN'
   
